/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-05-23 17:46:09 UTC)
 * on 2013-05-26 at 17:39:15 UTC 
 * Modify at your own risk.
 */

package com.appspot.ludounchained.controllerEndpoint.model;

/**
 * Model definition for Game.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Game extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key gameId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private User gameLeader;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private JsonMap users;

  /**
   * @return value or {@code null} for none
   */
  public Key getGameId() {
    return gameId;
  }

  /**
   * @param gameId gameId or {@code null} for none
   */
  public Game setGameId(Key gameId) {
    this.gameId = gameId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public User getGameLeader() {
    return gameLeader;
  }

  /**
   * @param gameLeader gameLeader or {@code null} for none
   */
  public Game setGameLeader(User gameLeader) {
    this.gameLeader = gameLeader;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public JsonMap getUsers() {
    return users;
  }

  /**
   * @param users users or {@code null} for none
   */
  public Game setUsers(JsonMap users) {
    this.users = users;
    return this;
  }

  @Override
  public Game set(String fieldName, Object value) {
    return (Game) super.set(fieldName, value);
  }

  @Override
  public Game clone() {
    return (Game) super.clone();
  }

}
